### ISSUE TITLE
pixelserv-tls ip address

### ISSUE THREAD

**Issue by PeterRob** [protik77/pixelserv-tls-arm#1]
Please add an option to set the pixelsrv-tls ip_addr

**Comment by protik77** [comment]
If you see the Dockerfile, there are two command line parameters are supplied while creating the image,
```
CMD ["-u", "root", "-l", "5"]
```
You can provide arguments in the `docker container run` command to override them. For example, if you want to provide `192.168.1.2 -u root -l 5` as command line arguments to `pixelserv-tls`, modify the `run_container.sh` to,
```bash
#!/bin/bash

SERVICE=rpi_pix
TAG=protik77/pixelserv-tls-arm

# stop if running
docker container stop $SERVICE

# remove container
docker container rm $SERVICE

docker container run \
    -d \
    --name $SERVICE \
    -p 80:80 \
    -p 443:443 \
    -v $(pwd)/cache:/var/cache/pixelserv \
    --restart unless-stopped \
    $TAG \
    192.168.1.2 -u root -l 5

docker container exec -it $SERVICE chown -R nobody /var/cache/pixelserv
```

I haven't tested it, but it should work. Please keep in mind that any additional argument in `docker container run` command will override the `CMD` arguments.
